name: Build Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t icons-app:latest .

      # Step 4: Save the Docker image as an artifact
      - name: Save Docker Image
        run: |
          docker save icons-app:latest -o icons-app.tar

      # Step 5: Upload the Docker image as an artifact
      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: icons-app
          path: icons-app.tar
